name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  plugin-test:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-14 # M1
          - macos-13 # Intel
        target:
          - tool-version: 'latest'
            command: 'makers --version && cargo-make make --version'
          # They are releasing aarch64 binary since 0.36.7: https://github.com/sagiegurari/cargo-make/commit/ab3cac2261c0ba67ab6d7a277aff8252faec0b1c
          - tool-version: '0.36.7'
            command: 'makers --version && cargo-make make --version'
          # Supporting olderst
          # https://github.com/kachick/asdf-cargo-make/blob/8a7095692e6a880568a5b48c441ea518ef6a61cb/bin/download#L12
          # https://github.com/kachick/asdf-cargo-make/blob/8a7095692e6a880568a5b48c441ea518ef6a61cb/lib/utils.bash#L59-L61
          - tool-version: '0.16.0'
            # makers does not exist
            command: 'cargo-make make --version'
        exclude:
          # They are releasing aarch64 binary since 0.36.7: https://github.com/sagiegurari/cargo-make/commit/ab3cac2261c0ba67ab6d7a277aff8252faec0b1c
          - os: macos-14
            target:
              - tool-version: '0.16.0'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: asdf-vm/actions/plugin-test@v3
        with:
          version: ${{ matrix.target.tool-version }}
          command: ${{ matrix.target.command }}
