name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  asdf:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-13 # Intel
        target:
          - tool-version: 'latest'
            command: 'makers --version && cargo-make make --version'
          # They are releasing aarch64 binary since 0.36.7: https://github.com/sagiegurari/cargo-make/commit/ab3cac2261c0ba67ab6d7a277aff8252faec0b1c
          - tool-version: '0.36.7'
            command: 'makers --version && cargo-make make --version'
          # Supporting olderst
          # https://github.com/kachick/asdf-cargo-make/blob/8a7095692e6a880568a5b48c441ea518ef6a61cb/bin/download#L12
          # https://github.com/kachick/asdf-cargo-make/blob/8a7095692e6a880568a5b48c441ea518ef6a61cb/lib/utils.bash#L59-L61
          - tool-version: '0.16.0'
            # makers does not exist
            command: 'cargo-make make --version'
        include:
          # They are releasing aarch64 binary since 0.36.7: https://github.com/sagiegurari/cargo-make/commit/ab3cac2261c0ba67ab6d7a277aff8252faec0b1c
          - os: macos-14 # M1
            target:
              tool-version: 'latest'
              command: 'makers --version && cargo-make make --version'
          - os: macos-14 # M1
            target:
              tool-version: '0.36.7'
              command: 'makers --version && cargo-make make --version'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: asdf-vm/actions/plugin-test@v3
        with:
          version: ${{ matrix.target.tool-version }}
          command: ${{ matrix.target.command }}

  mise:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-13 # Intel
        target:
          - command: |
              mise install cargo-make@latest
              mise x cargo-make@latest -- makers --version
              mise x cargo-make@latest -- cargo-make make --version
          # Supported oldest
          - command: |
              mise install cargo-make@0.16.0
              # makers does not exist
              mise x cargo-make@0.16.0 -- cargo-make make --version
        include:
          # They are releasing aarch64 binary since 0.36.7: https://github.com/sagiegurari/cargo-make/commit/ab3cac2261c0ba67ab6d7a277aff8252faec0b1c
          - os: macos-14 # M1
            target:
              command: |
                mise install cargo-make@latest
                mise x cargo-make@latest -- makers --version
                mise x cargo-make@latest -- cargo-make make --version
          - os: macos-14 # M1
            target:
              command: |
                mise install cargo-make@0.36.7
                mise x cargo-make@latest -- makers --version
                mise x cargo-make@latest -- cargo-make make --version
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          tool_versions: |
            # - This comment should have different value for each run to avoid the cache. See #75 and #77
            #   - avoid-cache-key: ${{ github.ref }}-${{ github.run_id }}-${{ github.run_attempt }}
            # - Don't set cargo-make versions here. Keep no tools for clean room test
      - name: Install plugin
        run: |
          mise plugins install cargo-make https://github.com/kachick/asdf-cargo-make.git#${{ github.ref }}
      - name: Test
        run: |
          ${{ matrix.target.command }}
