name: CI for dev env

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  tasks:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-14 # M1 # asdf-typos does not support yet https://github.com/aschiavon91/asdf-typos/blob/98babb263fc77a9d9f2aaebb257899c29cb4c5d4/bin/download#L21
          - macos-13 # Intel
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v3
      - run: |
          asdf plugin-add cargo-make https://github.com/kachick/asdf-cargo-make.git
          asdf plugin update cargo-make ${{ github.ref }} # https://github.com/asdf-vm/asdf/issues/1201
          asdf install cargo-make
          makers help
          makers setup
          makers check
