name: rtx
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  plugin-test:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        target:
          - rtx-tool-version: cargo-make@0.36.5
            command: rtx x ${{ matrix.target.rtx-tool-version }} -- makers --version && rtx x ${{ matrix.target.rtx-tool-version }} -- cargo-make make --version
          # https://github.com/kachick/asdf-cargo-make/blob/8a7095692e6a880568a5b48c441ea518ef6a61cb/bin/download#L12
          # https://github.com/kachick/asdf-cargo-make/blob/8a7095692e6a880568a5b48c441ea518ef6a61cb/lib/utils.bash#L59-L61
          - rtx-tool-version: cargo-make@0.16.0
            # makers does not exist
            command: 'rtx x ${{ matrix.target.rtx-tool-version }} cargo-make make --version'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: jdxcode/rtx-action@v1
        with:
          tool_versions: |
            # Should not set cargo-make versions here. (Actually shellcheck is not used here)
            shellcheck 0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup rtx
        run: |
          rtx plugins install cargo-make https://github.com/kachick/asdf-cargo-make.git#${{ github.ref }}
          rtx install ${{ matrix.target.rtx-tool-version }}
      - name: Test
        run: ${{ matrix.target.command }}
