name: rtx
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  plugin-test:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        target:
          - command: |
              rtx install cargo-make@latest
              rtx x cargo-make@latest -- makers --version
              rtx x cargo-make@latest -- cargo-make make --version
          # Supported oldest
          - command: |
              rtx install cargo-make@0.16.0
              # makers does not exist
              rtx x cargo-make@0.16.0 -- cargo-make make --version
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: jdxcode/rtx-action@v1.2.0
        with:
          tool_versions: |
            # - This comment should have different value for each run to avoid the cache. See #75 and #77
            #   - avoid-cache-key: ${{ github.ref }}-${{ github.run_id }}-${{ github.run_attempt }}
            # - Don't set cargo-make versions here. (Actually shellcheck is not used here, just a common plugin)
            shellcheck 0.9.0
      - name: Setup rtx
        run: |
          rtx plugins install cargo-make https://github.com/kachick/asdf-cargo-make.git#${{ github.ref }}
      - name: Test
        run: |
          ${{ matrix.target.command }}
        env:
          # https://github.com/jdxcode/rtx/issues/188#issuecomment-1441835716
          RTX_MISSING_RUNTIME_BEHAVIOR: autoinstall
